// <auto-generated />
using System;
using CardapioService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CardapioService.Migrations
{
    [DbContext(typeof(CardapioServiceContext))]
    partial class CardapioServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CardapioService.Model.Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemCardapioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemCardapioId");

                    b.ToTable("Adicional");
                });

            modelBuilder.Entity("CardapioService.Model.Cardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId")
                        .IsUnique();

                    b.ToTable("Cardapio");
                });

            modelBuilder.Entity("CardapioService.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCategoria")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("CardapioService.Model.ItemCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CardapioId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeItem")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardapioId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ItemCardapio");
                });

            modelBuilder.Entity("CardapioService.Model.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurante");
                });

            modelBuilder.Entity("CardapioService.Model.TipoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("AdicionalId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeItem")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdicionalId");

                    b.ToTable("TipoAdicional");
                });

            modelBuilder.Entity("CardapioService.Model.Adicional", b =>
                {
                    b.HasOne("CardapioService.Model.ItemCardapio", "ItemCardapio")
                        .WithMany("AdicionaisItem")
                        .HasForeignKey("ItemCardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCardapio");
                });

            modelBuilder.Entity("CardapioService.Model.Cardapio", b =>
                {
                    b.HasOne("CardapioService.Model.Restaurante", "Restaurante")
                        .WithOne("Cardapio")
                        .HasForeignKey("CardapioService.Model.Cardapio", "RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("CardapioService.Model.ItemCardapio", b =>
                {
                    b.HasOne("CardapioService.Model.Cardapio", "Cardapio")
                        .WithMany("ItensCardapio")
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardapioService.Model.Categoria", "CategoriaItem")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cardapio");

                    b.Navigation("CategoriaItem");
                });

            modelBuilder.Entity("CardapioService.Model.TipoAdicional", b =>
                {
                    b.HasOne("CardapioService.Model.Adicional", null)
                        .WithMany("TiposAdicionais")
                        .HasForeignKey("AdicionalId");
                });

            modelBuilder.Entity("CardapioService.Model.Adicional", b =>
                {
                    b.Navigation("TiposAdicionais");
                });

            modelBuilder.Entity("CardapioService.Model.Cardapio", b =>
                {
                    b.Navigation("ItensCardapio");
                });

            modelBuilder.Entity("CardapioService.Model.ItemCardapio", b =>
                {
                    b.Navigation("AdicionaisItem");
                });

            modelBuilder.Entity("CardapioService.Model.Restaurante", b =>
                {
                    b.Navigation("Cardapio");
                });
#pragma warning restore 612, 618
        }
    }
}
